### ISSUE TITLE
Start minimized (tray icon only)

### ISSUE THREAD

**Issue by Sam13** [SebastianBecker2/PowerPlanSwitcher#1]
I have created an autostart shortcut to launch the PPS tool on Windows startup.
Is there an option to start it minimized (tray icon only)?
Currently the configuration screen shows up.

Thanks

**Comment by SebastianBecker2** [comment]
There isn't an option to start the tool with the options showing. It always starts minimized (tray icon only).

Is it possible that you're actually using another tool? I did a bad job choosing the name. There are multiple with the same name. (In my defense, it's a rather obvious name.)
My options dialog look like this?
![image](https://github.com/SebastianBecker2/PowerPlanSwitcher/assets/35063968/f1b6ce34-0051-4c36-ba83-d728498aa1bb)

**Comment by Sam13** [comment]
Works with the release compile
