### ISSUE TITLE
Can't compare “AppsUseLightTheme”.

### ISSUE THREAD

**Issue by wuguo138428** [SebastianBecker2/PowerPlanSwitcher#18]
The original logic is still correct
It is wrong to judge by “AppsUseLightTheme”.
Try changing the
“AppsUseLightTheme” to 0.
“SystemUsesLightTheme” to 1.
Look at the file explorer and you'll see
![屏幕截图 2024-05-27 160351](https://github.com/SebastianBecker2/PowerPlanSwitcher/assets/106533733/ab617c81-1fc3-4c44-866d-6a0aa414d917)

**Comment by SebastianBecker2** [comment]
Uhhh I see what you mean. I considered it a regular application. But I get why you would expect to behave like the system setting and not like the app setting.
Yeah, I think it makes sense to change that. I will do.

**Comment by SebastianBecker2** [comment]
I changed it in main branch. It will be included in the next actual release.
