### ISSUE TITLE
Problems adding hotkey

### ISSUE THREAD

**Issue by HyraStylish** [SebastianBecker2/PowerPlanSwitcher#19]
I cannot set 'FN+F5' as the hotkey of cycling through power plans

**Comment by wuguo138428** [comment]
"FN" 不能作为任何软件程序的快捷键
"FN" 属于硬件快捷键,不在系统的标准键盘里

**Comment by SebastianBecker2** [comment]
Sadly, as @wuguo138428 has stated, it doesn't seem to be possible.
I could however use FN + F4 on a laptop. The F4 key was marked as 'Volume up'. So the app received a button press for the media key 'Volume up'.
The FN key press was not recognized was an actual key press. Just the combination with F4, in this case, sent a key press event for the media key.
So depending on your individual keyboard layout, you might use the FN key in combination with another key if it results in a key press event for the operating system.
Though keep in mind, in my case, the 'Volume up' was still executed by the operating system. Increasing the volume.
