### ISSUE TITLE
It would be even better if we could change the white or black theme

### ISSUE THREAD

**Issue by wuguo138428** [SebastianBecker2/PowerPlanSwitcher#2]
It would be even better if we could change the white or black theme
![屏幕截图 2024-05-10 155926](https://github.com/SebastianBecker2/PowerPlanSwitcher/assets/106533733/f08a670e-127b-4d05-8ddb-e6c6587e7f86)

I hope this popup will disappear automatically when you click anywhere, even if you don't click any  of the options.

I don't speak English well!sorry!sorry.

**Comment by wuguo138428** [comment]
![屏幕截图 2024-05-11 021702](https://github.com/SebastianBecker2/PowerPlanSwitcher/assets/106533733/8410aeea-b199-4b6b-b52d-da936418803c)
Repeatable start

**Comment by SebastianBecker2** [comment]
I added two color themes. Dark Mode (default) and Light Mode. Can be selected in the Settings Dialog.
And I made the popup disappear when you click anywhere else. (Except when you click on the Settings Dialog. It's a bit weird. But it should work in pretty much all situations.)

The program still doesn't avoid being started multiple times. I might do that another time. But really never had an issue with it. It's started automatically when Windows starts. So I never start it manually.

You can get the new version 1.0.5.0 here: https://github.com/SebastianBecker2/PowerPlanSwitcher/releases
Just install the new version. It replaces the old one. (After the install, you will have two tray icons. But as soon as you move the mouse over the old one, it disappears.)

If you have questions or other issues, just create a issue here. Your English is good enough. 👍
