### ISSUE TITLE
there's one small oversight.(Split Borders of Vision)

### ISSUE THREAD

**Issue by wuguo138428** [SebastianBecker2/PowerPlanSwitcher#7]
there's one small oversight.
"PowerSchemeSelectorDlg.Designer.cs -> private void InitializeComponent()"
add the following changes
"BackColor = Color.DarkGray;"
"Padding = new Padding(1);"
Otherwise there will be mixing with the background(Split Borders of Vision)

Before change
![屏幕截图 2024-05-13 142421](https://github.com/SebastianBecker2/PowerPlanSwitcher/assets/106533733/f6eac4fa-b986-46b5-b6f8-2b5feac98df6)
After the change
![屏幕截图 2024-05-13 142941](https://github.com/SebastianBecker2/PowerPlanSwitcher/assets/106533733/71e16362-0744-4384-bef0-e59d96f7e511)

**Comment by SebastianBecker2** [comment]
I added a pre-release version with the changes:
https://github.com/SebastianBecker2/PowerPlanSwitcher/releases/tag/v1.0.7.0-(visible-boarder)
The changes in the branch:
https://github.com/SebastianBecker2/PowerPlanSwitcher/tree/7-visible-boarder

I'm not 100% sure this is what you expected. Can you check if this is okay?
